// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IT_ASSET.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250128061051_allowNullablesForAssetIdsAndComputerIds")]
    partial class allowNullablesForAssetIdsAndComputerIds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Asset", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("UserAccountabilityListid")
                        .HasColumnType("int");

                    b.Property<string>("asset_barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("asset_image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("date_acquired")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("date_created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("date_modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("gpu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hdd")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("history")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("li_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("owner_id")
                        .HasColumnType("int");

                    b.Property<string>("po")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("serial_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ssd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("warranty")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("UserAccountabilityListid");

                    b.HasIndex("owner_id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("IT_ASSET.Models.Computer", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("UserAccountabilityListid")
                        .HasColumnType("int");

                    b.Property<string>("asset_barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("asset_image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("date_acquired")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("date_created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("date_modified")
                        .HasColumnType("datetime2");

                    b.Property<string>("gpu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hdd")
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("history")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("li_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("owner_id")
                        .HasColumnType("int");

                    b.Property<string>("po")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("serial_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ssd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("warranty")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("UserAccountabilityListid");

                    b.HasIndex("owner_id");

                    b.ToTable("computers");
                });

            modelBuilder.Entity("IT_ASSET.Models.ComputerComponents", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("asset_barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.PrimitiveCollection<string>("history")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("owner_id")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("owner_id");

                    b.ToTable("computer_components");
                });

            modelBuilder.Entity("IT_ASSET.Models.Logs.Asset_logs", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("asset_id")
                        .HasColumnType("int");

                    b.Property<string>("details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("performed_by_user_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("asset_id");

                    b.ToTable("asset_Logs");
                });

            modelBuilder.Entity("IT_ASSET.Models.Logs.User_logs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("performed_by_user_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("user_id");

                    b.ToTable("user_logs");
                });

            modelBuilder.Entity("IT_ASSET.Models.UserAccountabilityList", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("accountability_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("asset_ids")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("computer_ids")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("owner_id")
                        .HasColumnType("int");

                    b.Property<string>("tracking_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("owner_id");

                    b.ToTable("user_accountability_lists");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("date_created")
                        .HasColumnType("datetime2");

                    b.Property<string>("department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("e_signature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employee_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_active")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Asset", b =>
                {
                    b.HasOne("IT_ASSET.Models.UserAccountabilityList", null)
                        .WithMany("assets")
                        .HasForeignKey("UserAccountabilityListid");

                    b.HasOne("User", "owner")
                        .WithMany("assets")
                        .HasForeignKey("owner_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("owner");
                });

            modelBuilder.Entity("IT_ASSET.Models.Computer", b =>
                {
                    b.HasOne("IT_ASSET.Models.UserAccountabilityList", null)
                        .WithMany("computer")
                        .HasForeignKey("UserAccountabilityListid");

                    b.HasOne("User", "owner")
                        .WithMany("computer")
                        .HasForeignKey("owner_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("owner");
                });

            modelBuilder.Entity("IT_ASSET.Models.ComputerComponents", b =>
                {
                    b.HasOne("User", "owner")
                        .WithMany("computer_components")
                        .HasForeignKey("owner_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("owner");
                });

            modelBuilder.Entity("IT_ASSET.Models.Logs.Asset_logs", b =>
                {
                    b.HasOne("Asset", "assets")
                        .WithMany()
                        .HasForeignKey("asset_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("assets");
                });

            modelBuilder.Entity("IT_ASSET.Models.Logs.User_logs", b =>
                {
                    b.HasOne("User", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("IT_ASSET.Models.UserAccountabilityList", b =>
                {
                    b.HasOne("User", "owner")
                        .WithMany()
                        .HasForeignKey("owner_id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("owner");
                });

            modelBuilder.Entity("IT_ASSET.Models.UserAccountabilityList", b =>
                {
                    b.Navigation("assets");

                    b.Navigation("computer");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("assets");

                    b.Navigation("computer");

                    b.Navigation("computer_components");
                });
#pragma warning restore 612, 618
        }
    }
}
